const express=require('express');
const router=express.Router();

const User=require('../model/user');

//display the front page
router.get('/user',(req,res)=>{
    res.render('index');

});
//display the edit data page 
router.get('/change/user',(req,res)=>{
    res.render('change');

});

//to display all the users interested in coding
router.get('/user/coding',(req,res)=>{
    User.find({interests:"coding"}).then(function(data){
        console.log(data);
        var coding_users=data.map(user=>{
            return(user.name)
        });
       
        res.send(coding_users)
    }).catch(function(){
        res.send('no data found');
    });
});


//to display the page where one user can leave a comment
router.get('/user/comment',(req,res)=>{
    res.render('comment');
});

//to display comments left under a particular user's profile
router.get('/user/comment/:id',(req,res)=>{
    console.log(req.params.id);
    User.findOne({name:req.params.id}).then((user)=>{
        console.log(user.comments);
       
        res.send(user.comments);
    }).catch(function(){
        console.log('some error')
    });
});

//to create a new user using POST method
router.post('/user',(req,res)=>{
    res.send(req.body);
    User.create({
        name:req.body.name,
        email:req.body.email,
        phone_number:req.body.phone_number,
        address:req.body.address,
        interests:req.body.interests.split(' ')
    });
});

//to change the fields of a particular user using the id generated by mongodb ie edit user info
router.post('/change/user/',(req,res)=>{
    console.log(req.body._id)
    User.findByIdAndUpdate({_id:req.body._id},{$set:{
        name:req.body.name,
        email:req.body.email,
        phone_number:req.body.phone_number,
        address:req.body.address,
        interests:req.body.interests.split(' ')
    }},{new:true}).then((data)=>{
         console.log(data)
    }).catch(function(){
        res.send('error finding id')
    });
    res.send('done changing')
});

//to delete a user
router.post('/delete/user/',(req,res)=>{
    User.findByIdAndDelete({_id:req.body._id}).then(function(){
        res.send('data deleted')
    }).catch(function(){
        res.send('error finding id')
    });;

});


//to leave a comment under a particular user's profile
router.post('/user/comment',(req,res)=>{

    var data=req.body;
    console.log(data);
    res.send(data);
    User.findOne({name:req.body.to_user}).then((user)=>{
       if(user){
        console.log(user);
        var date=new Date();
            var comment_left ={
                from_user:req.body.from_user,
                to_user:req.body.to_user,
                comment:req.body.comment,
                time:date.toISOString()
            }
            console.log(comment_left)
            User.findOneAndUpdate({name:req.body.to_user},{$push:{comments:comment_left}},{new:true}).then(function(data){
                console.log('after comment is left',data)
            });
        }
        else{
            res.send(' to_user user not found');
        }
        
    });
});


module.exports=router